name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Pull and run Chroma Docker container
      run: |
        docker pull chromadb/chroma
        docker run -d -p 8000:8000 chromadb/chroma
    - name: Build Rust project
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Stop and remove Chroma Docker container
      run: |
        docker stop $(docker ps -q -f name=chroma)
        docker rm $(docker ps -aq -f name=chroma)
